//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystemBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public string FlightNumber { get; set; }
        public string NumOfTickets { get; set; }
        public Nullable<int> ProfileId { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
