//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystemBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public string Email { get; set; }
        public string Passport_Num { get; set; }
        public string Address { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string CreditCard { get; set; }
        public Nullable<int> IdOfUsers { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual User User { get; set; }
    }
}
